### ISSUE TITLE
Laravel 5.3?

### ISSUE THREAD

**Issue by kikemarto** [alfa6661/laravel-firebase#1]
Hi,

Suppor for Laravel 5.3?

Greetings.

**Comment by alfa6661** [comment]
Hi @kikemarto 

no.
i'm using [laravel notification backport for 5.2](https://github.com/laravel-notification-channels/backport) as dependency on this package.

will working on it next.

**Comment by alfa6661** [comment]
ah i just realized.
i think it should be working on 5.3, just remove 

```
"laravel-notification-channels/backport": "dev-master"
```

 from composer.json

I haven't had a chance to try

**Comment by kikemarto** [comment]
Thanks! I am going to try.
