### ISSUE TITLE
Bug in send to multiple device tokens

### ISSUE THREAD

**Issue by antonyharfield** [alfa6661/laravel-firebase#6]
Steps to recreate:
- implement routeNotificationForFirebase in your model
- when the model returns 2 device tokens then you will find this error

Expected result:
- each of the 2 devices will return 1 notification each

Actual result:
- the 1st device receives 1 notification
- the 2nd device receives 2 notification

I have tried to fix this and found the error is the addRecipent in the for loop in the send() method of FirebaseChannel. I solved the problem by changing it to:
```
public function send($notifiable, Notification $notification)
    {
        $devices = $notifiable->routeNotificationFor('firebase');
        if (empty($devices)) {
            return;
        }

        $firebase = $notification->toFirebase($notifiable);

        foreach ($devices as $device) {
            $this->message->addRecipient(new Device($device));
        }
        $this->message->setNotification($firebase->notification)->setData($firebase->data);

        try {
            $response = $this->client->send($this->message);
        } catch (Exception $e) {

        }
    }
```

**Comment by alfa6661** [comment]
Thanks 2fd10e56bf9b9bdfaca472c95bde5d485ca868e9
Sorry, i just got a chance to continue this project.

**Comment by pinguinjkeke** [comment]
@alfa6661 It's still not fixed. If you read code with attention, you'll see that you sending ```count($devices)``` messages to each device. Check out my PR with fix
